name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  fmt:
    name: 'terraform fmt'
    runs-on: ubuntu-latest
    defaults:
       run:
        shell: bash
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Terraform Format'
        uses: hashicorp/setup-terraform@v1
        with:
          actions_subcommand: 'fmt'

  init:
    name: 'terraform init'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Terraform init'
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          actions_subcommand: 'init'
         

  validate:
      name: 'terraform validate'
      runs-on: ubuntu-latest
      steps:
        - name: 'Checkout'
          uses: actions/checkout@v2.3.4

        - name: 'Terraform validate'
          uses: hashicorp/setup-terraform@v1.3.2
          with:
            actions_subcommand: 'validate'
           
      # - name: 'Terraform validate'
      #     uses: hashicorp/setup-terraform@v1.3.2
      #   with:
      #     actions_subcommand: 'validate'
      #     tf_actions_working_dir: ./_example
  plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      # - name: 'Terraform init'
      #   uses: hashicorp/setup-terraform@v1.3.2
      #   with:
      #     actions_subcommand: 'init'
      #     tf_actions_working_dir: ./_example

      - name: 'Terraform plan'
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          actions_subcommand: 'plan'
          
